### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by fabston** [impredicative/reticker#7]
Hi there,

I was wondering how the BLACKLIST works? I tried the  snippet mentioned in the readme but that is giving me `Cannot find reference 'config' in '__init__.py' `. I used:

```py
import reticker

reticker.config.BLACKLIST.add("EUR")
reticker.TickerExtractor().extract("EUR isn't a ticker, but URE is one.")
```

Appreciate your help.

**Comment by impredicative** [comment]
It works perfectly for me. Which version of Python are you using? Show the output of `python -V`. I just tested it with 3.10.7. Also, what did you use to install `reticker`?

**Comment by fabston** [comment]
I am using python 3.8. Can that be related to it? And I used pip to install reticker.

**Comment by impredicative** [comment]
Independent of this issue, I advise using the latest stable version of Python, currently 3.10.

Anyway, I tested it with 3.8, and I cannot reproduce the issue. If you cannot update to 3.10, at least ensure the version is 3.8.10.

```bash
$ python3.8 -m pip install reticker
Defaulting to user installation because normal site-packages is not writeable
Collecting reticker
  Downloading reticker-3.1.3-py3-none-any.whl (19 kB)
Installing collected packages: reticker
Successfully installed reticker-3.1.3
```

```
$ python3.8
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import reticker
>>> reticker.config.BLACKLIST.add("EUR")
>>> reticker.TickerExtractor().extract("EUR isn't a ticker, but URE is one.")
['URE']
```
