### ISSUE TITLE
Support unprefixed single letters, e.g. V

### ISSUE THREAD

**Issue by thomasgtaylor** [impredicative/reticker#8]
Single letters are matched when prefixed with `$`. Can this behavior be extended?

English words with single letters that will need to be blacklisted after this change:
- A
- I

**Comment by thomasgtaylor** [comment]
Thank you for your comment. To make sure I'm clear, I want to support 1 lettered stocks without requiring `$`. For example:
- O (Realty Income Corp)
- V (Visa)
- T (AT&T)

```python3
print(reticker.TickerExtractor().extract("My favorite stock is O"))
# []
print(reticker.TickerExtractor().extract("The best stock is V it's my favorite."))
# []
```

**Comment by thomasnotfound** [comment]
This is no problem. I can attempt with a PR.

**Comment by impredicative** [comment]
This is implemented and released.

In the US markets, "A" (Agilent) is a valid symbol with a non-negligible market cap, whereas "I" isn't. As such, "A" can't totally be blacklisted in the package itself, but perhaps "I" can.

In any case, as you know, you can choose to add "A" to the blacklist as a user as `reticker.config.BLACKLIST.add("A")`.
